# Generated by Django 5.0.6 on 2024-06-16 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uid', models.PositiveIntegerField(editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('designation', models.CharField(blank=True, choices=[('ED', 'ED'), ('GM', 'GM'), ('AGM', 'AGM'), ('MO', 'MO')], max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='photos/users')),
                ('role', models.CharField(blank=True, choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('Employee', 'Employee'), ('Accountant', 'Accountant'), ('Customer', 'Customer')], default='Employee', max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='usermanagement.useraccount')),
            ],
        ),
    ]
