# Generated by Django 5.0.6 on 2024-06-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_alter_useraccount_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name_plural': 'User Accounts'},
        ),
    ]
