# Generated by Django 5.0.6 on 2024-06-19 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('usermanagement', '0003_alter_useraccount_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('p_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('per_share_cost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCustomersModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('total_share', models.IntegerField()),
                ('have_to_pay_amount', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('paid', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_registered', to='usermanagement.useraccount')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.useraccount')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.projectsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCustomerInformationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('customer_image', models.ImageField(blank=True, null=True, upload_to='photos/customer')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_address', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phone1', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_nid_no', models.IntegerField()),
                ('customer_nid_image', models.ImageField(blank=True, null=True, upload_to='photos/customer')),
                ('customer_nominee_name', models.CharField(max_length=30)),
                ('customer_nominee_address', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_nominee_nid_image', models.ImageField(blank=True, null=True, upload_to='photos/customer')),
                ('customer_nominee_nid_no', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.projectcustomersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPaymentsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('booking_money', 'booking_money'), ('down_payment', 'down_payment'), ('installment', 'installment')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reference_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reference', to='usermanagement.useraccount')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_customer', to='usermanagement.useraccount')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.projectsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocumentsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('file_type', models.CharField(choices=[('jpg', 'jpg'), ('png', 'png'), ('pdf', 'pdf'), ('doc', 'doc'), ('csv', 'csv')], max_length=10, null=True)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='file/')),
                ('url', models.URLField(null=True)),
                ('pdoc_description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.projectsmodel')),
            ],
        ),
    ]
