# Generated by Django 5.0.6 on 2024-06-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='per_share_cost',
            field=models.IntegerField(),
        ),
    ]
