# Generated by Django 5.0.6 on 2024-06-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0002_alter_projectsmodel_per_share_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcustomerinformationmodel',
            name='customer_nid_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='projectcustomerinformationmodel',
            name='customer_nominee_nid_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='per_share_cost',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
