# Generated by Django 5.0.6 on 2024-06-21 19:31

import projectmanagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0004_alter_projectdocumentsmodel_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcustomersmodel',
            name='due_amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True, validators=[projectmanagement.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='projectcustomersmodel',
            name='have_to_pay_amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True, validators=[projectmanagement.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='projectcustomersmodel',
            name='paid',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True, validators=[projectmanagement.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='projectcustomersmodel',
            name='total_share',
            field=models.IntegerField(validators=[projectmanagement.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='projectpaymentsmodel',
            name='amount',
            field=models.IntegerField(blank=True, null=True, validators=[projectmanagement.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='per_share_cost',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[projectmanagement.models.validate_non_negative]),
        ),
    ]
