# Generated by Django 5.0.6 on 2024-06-21 19:33

import projectmanagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0005_projectcustomersmodel_due_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcustomersmodel',
            name='paid',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True, validators=[projectmanagement.models.validate_non_negative]),
        ),
    ]
