# Generated by Django 5.0.6 on 2024-06-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0006_alter_projectcustomersmodel_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcustomersmodel',
            name='due_amount',
        ),
    ]
